# Generated by Django 2.1.7 on 2019-03-24 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_feed', models.CharField(max_length=400)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('title', models.TextField(blank=True)),
                ('title_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('published_parsed', models.DateTimeField(blank=True, null=True)),
                ('is_entities_parsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-published_parsed',),
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_translit', models.CharField(max_length=100)),
                ('entity_class', models.CharField(choices=[('PER', 'Person'), ('ORG', 'Organisation'), ('LOC', 'Location')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='feed_name')),
                ('url', models.URLField(max_length=2048, unique=True, verbose_name='feed address')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeedEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeedner.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_entities',
            field=models.ManyToManyField(to='newsfeedner.FeedEntities'),
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeedner.Feed'),
        ),
    ]
